CREATE DATABASE BOOK_STORE;
GO

USE BOOK_STORE;
GO

CREATE TABLE USERS (
		USER_ID INT IDENTITY (1, 1) NOT NULL,
		FULL_NAME NVARCHAR (100) NOT NULL,
		EMAIL VARCHAR(100) NOT NULL,
		PASSWORD_HASH VARCHAR(255) NOT NULL,
		PHONE VARCHAR(15) NULL,
		ADDRESS NVARCHAR (255) NULL,
		ROLE VARCHAR(10) CHECK (ROLE IN ('USER', 'ADMIN')) DEFAULT 'USER',
		IS_ACTIVE BIT NULL DEFAULT 1,
		CREATED_AT DATETIME DEFAULT GETDATE(),
		UPDATED_AT DATETIME DEFAULT GETDATE(),
		PRIMARY KEY (USER_ID)
);

CREATE TABLE CATEGORIES (
		CATEGORY_ID INT IDENTITY (1, 1) NOT NULL,
		CATEGORY_NAME NVARCHAR (100) NOT NULL,
		PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE PUBLISHERS (
		PUBLISHER_ID INT IDENTITY (1, 1) NOT NULL,
		PUBLISHER_NAME NVARCHAR (150) NOT NULL,
		COUNTRY NVARCHAR (50) NULL,
		PRIMARY KEY (PUBLISHER_ID)
);

CREATE TABLE AUTHORS (
		AUTHOR_ID INT IDENTITY (1, 1) NOT NULL,
		AUTHOR_NAME NVARCHAR (100) NOT NULL,
		BIO NVARCHAR (4000),
		PRIMARY KEY (AUTHOR_ID)
);

CREATE TABLE BOOKS (
		BOOK_ID INT IDENTITY (1, 1) NOT NULL,
		BOOK_NAME NVARCHAR (255) NOT NULL,
		DESCRIPTION NVARCHAR (MAX) NOT NULL,
		PUBLISH_YEAR INT NULL,
		LANGUAGE NVARCHAR (50) NULL,
		PAGES INT NULL,
		IMAGE VARCHAR(255) NOT NULL,
		QUANTITY INT NOT NULL,
		PRICE DECIMAL(12, 2) NOT NULL,
		CATEGORY_ID INT NOT NULL,
		PUBLISHER_ID INT NULL,
		AUTHOR_ID INT NOT NULL,
		IS_DELETED BIT DEFAULT 0,
		CREATED_AT DATETIME DEFAULT GETDATE(),
		UPDATED_AT DATETIME DEFAULT GETDATE(),
		PRIMARY KEY (BOOK_ID),
		FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID),
		FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS (PUBLISHER_ID),
		FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (AUTHOR_ID)
);

CREATE TABLE CARTS (
		CART_ID INT IDENTITY (1, 1) NOT NULL,
		USER_ID INT NOT NULL,
		CREATED_AT DATETIME DEFAULT GETDATE(),
		UPDATED_AT DATETIME DEFAULT GETDATE(),
		PRIMARY KEY (CART_ID),
		FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE CART_ITEMS (
		CART_ITEM_ID INT IDENTITY (1, 1) NOT NULL,
		CART_ID INT NOT NULL,
		BOOK_ID INT NOT NULL,
		QUANTITY INT NOT NULL,
		ADDED_AT DATETIME DEFAULT GETDATE(),
		PRIMARY KEY (CART_ITEM_ID),
		FOREIGN KEY (CART_ID) REFERENCES CARTS (CART_ID),
		FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID)
);

CREATE TABLE ORDERS (
		ORDER_ID INT IDENTITY (1, 1) NOT NULL,
		USER_ID INT NOT NULL,
		RECEIVER_NAME NVARCHAR (100) NOT NULL,
		RECEIVER_PHONE VARCHAR(15) NOT NULL,
		SHIPPING_ADDRESS NVARCHAR (255) NOT NULL,
		ORDER_DATE DATETIME DEFAULT GETDATE(),
		TOTAL_AMOUNT DECIMAL(12, 2) NOT NULL,
		STATUS VARCHAR(20) CHECK (STATUS IN ('Pending', 'Completed', 'Cancelled')) DEFAULT 'Pending',
		PAYMENT_METHOD VARCHAR(20) NULL,
		PRIMARY KEY (ORDER_ID),
		FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE ORDER_DETAILS (
		ORDER_DETAIL_ID INT IDENTITY (1, 1) NOT NULL,
		ORDER_ID INT NOT NULL,
		BOOK_ID INT NULL,
		QUANTITY INT NOT NULL,
		PRICE DECIMAL(12, 2) NOT NULL,
		PRIMARY KEY (ORDER_DETAIL_ID),
		FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
		FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID)
);
